version: 0.0
os: linux

files:
  - source: /flaskapp
    destination: /home/ubuntu/flaskapp

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
