version: 0.0
os: linux

files:
  - source: /flaskapp
    destination: /home/ubuntu/flaskapp

  - source: params.yaml
    destination: /home/ec2-user/

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
